import type { Metadata } from "next";
import { getLocaleFromPath } from "@/lib/i18n";
import { buildMetadata } from "@/lib/seo";

type Props = {
  params: { locale: string };
};

export function generateMetadata({ params }: Props): Metadata {
  const locale = getLocaleFromPath(params.locale);
  return buildMetadata({
    locale,
    title: locale === "tr" ? "SSS - Global AI Araçları" : "FAQ - Global AI Tools",
    description:
      locale === "tr"
        ? "Global AI Araçları hakkında sık sorulan sorular."
        : "Frequently asked questions about Global AI Tools.",
    pathWithoutLocale: "/faq",
  });
}

export default function FaqPage({ params }: Props) {
  const locale = getLocaleFromPath(params.locale);

  const items = locale === "tr"
    ? [
        {
          q: "Araçlar nasıl listeleniyor?",
          a: "Kaynak taraması, otomasyon ve editoryal kalite kontrol ile düzenli olarak güncellenir.",
        },
        {
          q: "Karşılaştırmalar neye göre hazırlanıyor?",
          a: "Kategori uyumu, güncellik, kullanım senaryosu ve fiyat/performans sinyallerine göre hazırlanır.",
        },
        {
          q: "Reklam veya iş birliği için nasıl ulaşabilirim?",
          a: "atacsinem21@gmail.com adresine e-posta gönderebilirsiniz.",
        },
      ]
    : [
        {
          q: "How are tools listed?",
          a: "Listings are updated via source ingestion automation plus editorial quality checks.",
        },
        {
          q: "How are comparisons prepared?",
          a: "Comparisons are generated by category relevance, freshness, and use-case fit.",
        },
        {
          q: "How can I contact you for advertising or partnerships?",
          a: "Please email atacsinem21@gmail.com.",
        },
      ];

  return (
    <section className="space-y-5">
      <h1 className="text-3xl font-bold text-slate-100">{locale === "tr" ? "Sik Sorulan Sorular" : "Frequently Asked Questions"}</h1>
      <div className="space-y-3">
        {items.map((item) => (
          <details key={item.q} className="rounded-xl border border-slate-800 bg-slate-900 p-4">
            <summary className="cursor-pointer font-medium text-slate-100">{item.q}</summary>
            <p className="mt-2 text-sm text-slate-300">{item.a}</p>
          </details>
        ))}
      </div>
    </section>
  );
}
